baseurl = "http://krig.github.io/"
title = "krig"
languageCode = "en-us"
MetaDataFormat = "yaml"
copyright = "Copyright (c) 2017, Kristoffer Gr&ouml;nlund"

[author]
name = "Kristoffer Gr&ouml;nlund"
