name = "Krigs"
license = "MIT"
licenselink = "https://github.com/krigs/krigs-hugo-theme/blob/master/LICENSE.md"
description = "Theme for http://kri.gs/"
homepage = "http://kri.gs/"
tags = ["", ""]
features = ["", ""]
min_version = 0.14

[author]
  name = "Kristoffer Gronlund"
  homepage = "http://kri.gs/"
